var music=[
    {
        id:01,
        name:"信",
        songer:'Davichi',
        picUlr:'music/01.mp3',
    },
    {
        id:02,
        name:"你不是真正的快乐",
        songer:'邓紫棋',
        picUlr:'music/02.mp3',
    },
    {
        id:03,
        name:"烟火里的尘埃",
        songer:'华晨宇',
        picUlr:'music/03.mp3',
    },
    {
        id:04,
        name:"Trap",
        songer:'刘宪华（Henry）',
        picUlr:'music/04.mp3',
    },
    {
        id:05,
        name:"下个路口见",
        songer:'李宇春',
        picUlr:'music/05.mp3',
    },
    {
        id:06,
        name:"棉花糖",
        songer:'至上励合',
        picUlr:'music/06.mp3',
    },
    {
        id:07,
        name:"I knew you were",
        songer:'泰勒.斯威夫特',
        picUlr:'music/07.mp3',
    },
    {
        id:08,
        name:"像我这样的人",
        songer:'毛不易',
        picUlr:'music/08.mp3',
    },
];